# Generated by Django 2.2.5 on 2019-10-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20191008_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='folio',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
